// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mooszrrpyngdksthdrqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vb3N6cnJweW5nZGtzdGhkcnF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODg5NTksImV4cCI6MjA2NTY2NDk1OX0.P7NBbrHdwCgDL_7BKOyh91q0eePsr_sBw6gemrGo68Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);